# Generated by Django 5.1.1 on 2024-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
