# Generated by Django 5.1.1 on 2024-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_alter_route_route_id_alter_trip_trip_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="user_id",
            field=models.CharField(),
        ),
    ]
