# Generated by Django 5.1.1 on 2024-10-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_alter_trip_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["route_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("user_id", "route_name")},
        ),
    ]
